package commom;
//là 1 kiểu dữ diệu dang liêt kế , liếtj kê danh sách các hàng
public enum PageType {

 USER_MANAGEMENT_PAGE,VIDEO_MANAGEMENT_PAGE,REPORTS_MANAGEMENT_PAGE,HOME_MANAGEMENT_PAGE,HOME_MOVIE_PAGE,LIST_MOVIE_PAGE,DETAILS_MOVIE_PAGE
 ,WATCH_MOVIE_PAGE,LOGIN_MOVIE_PAGE,SHASE_MOVIE_PAGE,
 SIGN_UP_MOVIE_PAGE,EDIT_PROFILE_PAGE,FORGOT_PASSWORD_MOVIE_PAGE,CHANGE_PASSWORD_PAGE

}
